---
- name: Find VMs with mounted CD/DVD media on ESXi
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    esxi_hostname: "10.10.10.3"
    esxi_username: "{{ lookup('env', 'VMWARE_USER') }}"
    esxi_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false

  tasks:

    - name: Get list of VMs from ESXi
      vmware_vm_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_info

    - name: Initialize list of VMs with CD media
      set_fact:
        vms_with_cdrom: []

    - name: Check each VM for connected CD/DVD devices
      vars:
        cd_devices: >-
          {{
            item.hardware.device | selectattr('device_info.label', 'search', 'CD/DVD') | list
          }}
        cd_connected: >-
          {{
            cd_devices | selectattr('connectable.connected', 'equalto', true) | list
          }}
        cd_backings: >-
          {{
            cd_connected | map(attribute='backing.fileName') | list
          }}
      set_fact:
        vms_with_cdrom: "{{ vms_with_cdrom + [ { 'name': item.name, 'iso_files': cd_backings } ] }}"
      when: cd_connected | length > 0
      loop: "{{ vm_info.virtual_machines }}"

    - name: Show VMs with CD/DVD mounted
      debug:
        var: vms_with_cdrom
