---
- name: Find VMs with mounted CD/DVD media on ESXi
  hosts: localhost
  gather_facts: no

  vars:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false

  tasks:
    - name: Retrieve all VMs from vCenter/ESXi
      vmware_vm_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_info

    - name: Initialize result list
      set_fact:
        vms_with_connected_cd: []

    - name: Check each VM for connected CD/DVD device
      vars:
        vm_devices: "{{ item.hardware.device | default([]) }}"
        cd_devices: >-
          {{
            vm_devices
            | selectattr('device_info.label', 'search', 'CD/DVD')
            | selectattr('connectable', 'defined')
            | list
          }}
        has_connected_cd: >-
          {{
            cd_devices
            | selectattr('connectable.connected', 'defined')
            | selectattr('connectable.connected', 'equalto', true)
            | list
          }}
      set_fact:
        vms_with_connected_cd: "{{ vms_with_connected_cd + [item] }}"
      when: has_connected_cd | length > 0
      loop: "{{ vm_info.virtual_machines }}"
      loop_control:
        label: "{{ item.guest_name | default(item.vm_name) }}"

    - name: Print VMs with connected CD/DVD devices
      debug:
        msg: "VM '{{ item.guest_name | default(item.vm_name) }}' has connected CD/DVD device(s)."
      loop: "{{ vms_with_connected_cd }}"
