---
- name: Find VMs with ISO files mounted to CD drives
  hosts: all
  gather_facts: false
  connection: local
  
  vars:
    # AAP credential variables - these will be injected by AAP
    vcenter_username: "{{ ansible_user }}"
    vcenter_password: "{{ ansible_password }}"
    
  tasks:
    - name: Gather information about all VMs on ESXi host
      community.vmware.vmware_vm_info:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        vm_type: vm
        show_attribute: true
      register: vm_info
      delegate_to: localhost

    - name: Get VM hardware details for each VM
      community.vmware.vmware_guest_info:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        uuid: "{{ item.uuid }}"
        schema: "vsphere"
        properties:
          - "config.hardware.device"
      register: vm_hardware_details
      loop: "{{ vm_info.virtual_machines }}"
      delegate_to: localhost

    - name: Display VM hardware structure for debugging
      debug:
        msg: "VM: {{ vm_info.virtual_machines[0].guest_name }}, Hardware keys: {{ vm_hardware_details.results[0].instance.keys() | list }}"
      when: 
        - vm_info.virtual_machines | length > 0
        - vm_hardware_details.results | length > 0
        - vm_hardware_details.results[0].instance is defined

    - name: Check each VM for CD devices manually (simple approach)
      debug:
        msg: |
          Checking VM: {{ vm_info.virtual_machines[item].guest_name }}
          Power State: {{ vm_info.virtual_machines[item].power_state }}
          Hardware available: {{ vm_hardware_details.results[item].instance.config is defined }}
      loop: "{{ range(0, vm_info.virtual_machines|length) | list }}"
      when: vm_hardware_details.results[item].instance is defined

    - name: Simple summary
      debug:
        msg: |
          ===================================================
          ESXi Host: {{ inventory_hostname }}
          Total VMs found: {{ vm_info.virtual_machines | length }}
          ===================================================