---
- name: Find VMs with mounted CD/DVD media on ESXi
  hosts: localhost
  gather_facts: no


  vars:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false

  tasks:
    - name: Retrieve all VMs from vCenter/ESXi
      vmware_vm_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_info

