---
- name: Find VMs with mounted CD/DVD media on ESXi
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    esxi_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    esxi_username: "{{ lookup('env', 'VMWARE_USER') }}"
    esxi_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false

  tasks:

    - name: Get list of VMs from ESXi
      vmware_vm_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_info

    - name: Find VMs with CD/DVD mounted
      set_fact:
        vms_with_cd: >-
          {{
            vm_info.virtual_machines | selectattr('hardware.device', 'defined') | selectattr('hardware.device', 'select',
              lambda devs: devs | selectattr('device_info.label', 'search', 'CD/DVD')
                            | selectattr('connectable.connected', 'equalto', true)
                            | list
              ) | list
          }}

    - name: Show VMs with mounted CD/DVD
      debug:
        msg: "{{ item.name }}"
      loop: "{{ vms_with_cd }}"
