---
- name: Find VMs with CD/DVD media mounted on standalone ESXi
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    esxi_hostname: "10.10.10.3"  # Replace with your ESXi IP or hostname
    esxi_username: "{{ lookup('env', 'ESXI_USERNAME') }}"  # Or hardcode
    esxi_password: "{{ lookup('env', 'ESXI_PASSWORD') }}"
    validate_certs: false

  tasks:

    - name: Get list of all virtual machines on ESXi
      vmware_vm_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_info

    - name: Filter VMs with CD/DVD devices that are connected and have backing file
      set_fact:
        vms_with_cdrom: >-
          {{
            vm_info.virtual_machines | selectattr('hardware.device', 'defined') | selectattr(
              'hardware.device',
              'select',
              lambda devices: devices | selectattr('device_info.label', 'search', 'CD/DVD') | selectattr('connectable.connected', 'equalto', true) | list | length > 0
            ) | list
          }}

    - name: Display VMs with CD/DVD mounted media
      debug:
        msg: >-
          VM: {{ item.name }},
          ISO: {{
            item.hardware.device | selectattr('device_info.label', 'search', 'CD/DVD')
            | selectattr('connectable.connected', 'equalto', true)
            | map(attribute='backing.fileName') | list
          }}
      loop: "{{ vms_with_cdrom }}"
