---
- name: List VMs with snapshots on ESXi
  hosts: localhost
  gather_facts: no

  vars:
    validate_certs: false

  tasks:
    - name: Get detailed list of all VMs (including UUIDs)
      vmware_vm_info:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: "{{ validate_certs }}"
      register: vms

    - name: Get snapshot info for each VM
      vmware_guest_snapshot_info:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: "Virtual machine"
        uuid: "{{ item.uuid }}"
        validate_certs: "{{ validate_certs }}"
      loop: "{{ vms.virtual_machines }}"
      register: snapshot_results

    - name: Show VMs with snapshots
      debug:
        msg: "VM {{ item.invocation.module_args.uuid }} has snapshots"
      loop: "{{ snapshot_results.results }}"
      when: item.snapshot_info is defined and item.snapshot_info.snapshots | length > 0
