---
- name: List VMs with snapshots on ESXi
  hosts: localhost
  gather_facts: no
  #collections:
  #  - community.vmware

  vars:
  #  esxi_host: "192.168.1.100"
  #  esxi_user: "root"
  #  esxi_pass: "your_password"
    validate_certs: false

  tasks:
    - name: Get detailed list of all VMs (including snapshots)
      vmware_vm_info:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        validate_certs: "{{ validate_certs }}"

      register: vms

    - name: Get list of all VMs on ESXi host
      vmware_guest_snapshot_info:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: "Virtual machine"
        name: "unifi-orig"
        validate_certs: "{{ validate_certs }}"
      delegate_to: localhost  
      register: vm_info

    # - name: Filter VMs that have snapshots
    #   set_fact:
    #     vms_with_snapshots: "{{ vm_info.virtual_machines | selectattr('snapshots', 'defined') }}" #| selectattr('snapshots', '!=', []) | list }}"

    # - name: Show VMs with snapshots
    #   debug:
    #     msg: "VM {{ item.name }} has snapshots"
    #   loop: "{{ vms_with_snapshots }}"
      
