---
- name: List VMs with snapshots on ESXi
  hosts: localhost
  gather_facts: no
  #collections:
  #  - community.vmware

  vars:
  #  esxi_host: "192.168.1.100"
  #  esxi_user: "root"
  #  esxi_pass: "your_password"
    validate_certs: false

  tasks:
    - name: Get detailed list of all VMs (including snapshots)
      vmware_vm_info:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: "{{ validate_certs }}"

      register: vms

    - name: Get list of all VMs on ESXi host
      vmware_guest_snapshot_info:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: "Virtual machine"
        uuid: "{{ item.uuid }}"
        validate_certs: "{{ validate_certs }}"
      delegate_to: localhost  
      register: vm_info
      loop: "{{ vms.virtual_machines }}"


    - name: Show VMs with snapshots
      debug:
        msg: "VM {{ item.name }} has snaxpsots"
      loop: "{{ vm_info }}"
      
