---
- name: Gather facts from Ubuntu Desktop
<<<<<<< HEAD
  hosts: 10.10.10.174
  become: yes  # Run tasks with sudo
=======
  hosts: all
  remote_user: igumas
  become: no  # Run tasks with sudo
  become_method: sudo
  become_user: igumas  
>>>>>>> 5085cd6c1eab13dd18ee1b4854951e4909e139de

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - all

    - name: Display gathered facts 
      ansible.builtin.debug:
        var: ansible_facts
