---
- name: Gather facts from Ubuntu Desktop
  hosts: all
  become: no  # Run tasks with sudo
  become_method: su
  become_user: root
  become_pass: 'Citl0ml!'

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - all

    - name: Display gathered facts 
      ansible.builtin.debug:
        var: ansible_facts
