---
- name: Gather VM network details from ESXi host
  hosts: localhost
  gather_facts: no
  vars:
    esxi_host: "10.10.10.2"
    esxi_user: "root"
    esxi_password: "Citl0ml!"
  tasks:
    - name: Get VM facts from ESXi
      community.vmware.vmware_vm_info:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
      register: vm_info

    - name: Create array of dictionaries with VM names and network names
      set_fact:
        vm_networks: "{{ vm_info.virtual_machines | map('extract', 'name') | zip(vm_info.virtual_machines | map(attribute='networks.0.network')) | list | map('list', ['vm_name', 'net_name']) | list }}"

    - name: Show the VM networks array
      debug:
        var: vm_networks
