---
- name: Gather facts from Ubuntu Desktop
  hosts: all
  become: no  # Run tasks with sudo
  become_method: sudo
  become_user: igumas
  ansible_user: igumas
  

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - all

    - name: Display gathered facts 
      ansible.builtin.debug:
        var: ansible_facts
