---
- name: Gather facts from Ubuntu Desktop
  hosts: all
  become: no  # Run tasks with sudo

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - all

    - name: Display gathered facts 
      ansible.builtin.debug:
        var: ansible_facts
