---
- name: Gather system information from Windows host
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather Windows system information
      ansible.windows.win_command:
        cmd: systeminfo
      register: system_info

    - name: Display system information
      ansible.builtin.debug:
        msg: "{{ system_info.stdout_lines }}"

    - name: Gather disk information
      ansible.windows.win_shell:
        cmd: wmic logicaldisk get caption,description,filesystem,freespace,size
      register: disk_info

    - name: Display disk information
      ansible.builtin.debug:
        msg: "{{ disk_info.stdout_lines }}"

    - name: Gather CPU information
      ansible.windows.win_shell:
        cmd: wmic cpu get caption,deviceid,maxclockspeed,manufacturer
      register: cpu_info

    - name: Display CPU information
      ansible.builtin.debug:
        msg: "{{ cpu_info.stdout_lines }}"

    - name: Gather memory information
      ansible.windows.win_shell:
        cmd: wmic memorychip get capacity,manufacturer,speed
      register: memory_info

    - name: Display memory information
      ansible.builtin.debug:
        msg: "{{ memory_info.stdout_lines }}"