---
- name: Gather system information from Windows 11 host
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather Windows system information
      ansible.windows.win_shell:
        cmd: systeminfo
      register: system_info

    - name: Display system information
      ansible.builtin.debug:
        msg: "{{ system_info.stdout_lines }}"

    - name: Gather disk information
      ansible.windows.win_shell:
        cmd: Get-CimInstance Win32_LogicalDisk | Select-Object DeviceID,Description,FileSystem,FreeSpace,Size | Format-Table -AutoSize | Out-String
      register: disk_info

    - name: Display disk information
      ansible.builtin.debug:
        msg: "{{ disk_info.stdout_lines }}"

    - name: Gather CPU information
      ansible.windows.win_shell:
        cmd: Get-CimInstance Win32_Processor | Select-Object Name,DeviceID,MaxClockSpeed,Manufacturer | Format-Table -AutoSize | Out-String
      register: cpu_info

    - name: Display CPU information
      ansible.builtin.debug:
        msg: "{{ cpu_info.stdout_lines }}"

    - name: Gather memory information
      ansible.windows.win_shell:
        cmd: Get-CimInstance Win32_PhysicalMemory | Select-Object Capacity,Manufacturer,Speed | Format-Table -AutoSize | Out-String
      register: memory_info

    - name: Display memory information
      ansible.builtin.debug:
        msg: "{{ memory_info.stdout_lines }}"