---
- name: Test win_shell
  hosts: spiderman.3pierces.com
  gather_facts: false
  tasks:
    - name: Debug test command
      ansible.builtin.debug:
        msg: "Executing command: dir"
    - name: Test command
      ansible.windows.win_shell:
        cmd: dir
      register: result
    - name: Display result
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"