---
# Alternative approach: Attempt disconnect on ALL CD devices with force

- name: Disconnect ALL CD devices (ignore hot_removable status with force)
  community.vmware.vmware_guest:
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    uuid: "{{ item.0.uuid }}"
    force: "{{ force_disconnect | default(true) }}"
    cdrom:
      - controller_number: "{{ item.1.controller_number }}"
        unit_number: "{{ item.1.unit_number }}"
        state: present
        type: none
  with_subelements:
    - "{{ vms_eligible_for_disconnect }}"
    - cd_devices
  loop_control:
    label: "{{ item.0.vm_name }} - {{ item.1.device_label }}"
  delegate_to: localhost
  when: 
    - not (dry_run | bool)
    # Removed the hot_removable condition entirely
  register: disconnect_results
  failed_when: false
  retries: 3
  delay: 5a