---
#===============================================================================
# Final Operation Summary and Reporting
#===============================================================================
# Purpose: Calculate and display comprehensive summary of all operations
# Called by: cdmounted.yml main playbook (final step)
#
# Description:
#   This task file provides the final summary of all operations performed
#   during the playbook execution. It calculates statistics, identifies
#   blacklisted VMs, and reports on any failed operations or queries.
#
# Summary Includes:
#   - Total VMs scanned and found with CD devices
#   - Blacklisted VM details
#   - Disconnect operation results (if performed)
#   - Failed VM queries and operations
#   - Operation mode (dry run vs live)
#
# Variables Used:
#   - vm_info: VM discovery results
#   - vms_with_cd_media: VMs with connected CD devices
#   - vm_blacklist: Excluded VMs
#   - disconnect_results: Results from disconnect operations (if available)
#   - failed_vm_queries: VMs that failed hardware queries
#===============================================================================

#-------------------------------------------------------------------------------
# Summary Statistics Calculation
#-------------------------------------------------------------------------------
# Calculate key metrics for the final operation summary
- name: Calculate summary statistics
  ansible.builtin.set_fact:
    total_vms_found: "{{ vm_info.virtual_machines | length }}"
    blacklisted_vms: "{{ vms_with_cd_media | selectattr('vm_name', 'in', vm_blacklist) | list }}"
    successful_disconnects: >-
      {{
        disconnect_results.results | default([]) |
        selectattr('changed', 'equalto', true) |
        list
      }}

#-------------------------------------------------------------------------------
# Comprehensive Operation Summary
#-------------------------------------------------------------------------------
# Display detailed summary of all operations performed on the ESXi host
- name: Display operation summary
  ansible.builtin.debug:
    msg: |
      ===================================================
      OPERATION SUMMARY for {{ inventory_hostname }}:
      ===================================================
      Mode: {{ 'DRY RUN' if dry_run else 'LIVE' }}
      Total VMs scanned: {{ total_vms_found }}
      VMs with connected CD devices: {{ vms_with_cd_media | length }}
      VMs in blacklist: {{ blacklisted_vms | length }}
      Failed VM queries: {{ failed_vm_queries | length }}
      Disconnect operations: {{ 'Enabled' if disconnect else 'Disabled' }}
      {% if not dry_run and disconnect and vms_with_cd_media | length > 0 %}
      Successful disconnects: {{ successful_disconnects | length }}
      {% endif %}
      
      {% if blacklisted_vms | length > 0 %}
      Blacklisted VMs with CD media:
      {% for vm in blacklisted_vms %}
      - {{ vm.vm_name }} ({{ vm.cd_devices | length }} devices)
      {% endfor %}
      {% endif %}
      ===================================================

#-------------------------------------------------------------------------------
# Failed Operations Reporting
#-------------------------------------------------------------------------------
# Report details about any failed VM queries or operations
# Helps identify VMs that may need manual attention
- name: Report any failed operations
  ansible.builtin.debug:
    msg: |
      ===================================================
      FAILED OPERATIONS:
      ===================================================
      {% for failure in failed_vm_queries %}
      VM: {{ failure.vm_name }}
      Error: {{ failure.error }}
      {% endfor %}
      ===================================================
  when: failed_vm_queries | length > 0