---
- name: Query VM hardware information
  community.vmware.vmware_guest_info:
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    uuid: "{{ vm_item.uuid }}"
    schema: "vsphere"
    properties:
      - "config.hardware.device"
  register: vm_hardware
  delegate_to: localhost
  failed_when: false
  retries: 2
  delay: 2

- name: Record failed VM query
  ansible.builtin.set_fact:
    failed_vm_queries: >-
      {{
        failed_vm_queries + [{
          'vm_name': vm_item.guest_name | default('Unknown'),
          'uuid': vm_item.uuid,
          'error': vm_hardware.msg | default('Hardware query failed')
        }]
      }}
  when: vm_hardware.failed is defined and vm_hardware.failed

- name: Process VM hardware to find CD devices
  ansible.builtin.include_tasks: tasks/find_cd_devices.yml
  when:
    - vm_hardware.failed is not defined or not vm_hardware.failed
    - vm_hardware.instance is defined
    - vm_hardware.instance.config is defined
    - vm_hardware.instance.config.hardware is defined